### ISSUE TITLE
Mass assignment errors for :action and :modifications

### ISSUE THREAD

**Issue by robrobbins** [harley/auditable#10]
was getting:

ActiveModel::MassAssignmentSecurity::Error:
       Can't mass-assign protected attributes: action, modifications

so I did (app/models/auditable/audit_decorator.rb) :

Auditable::Audit.class_eval do
  attr_accessible :action, :modifications
end

Works. But,  I'd rather not have to decorate it.

**Comment by harley** [comment]
thank you! will fix that

**Comment by robrobbins** [comment]
Np! changed_by may need it as well...

**Comment by harley** [comment]
thanks. i wonder if there's an easy way to test this besides creating a rails dummy app with `config.active_record.mass_assignment_sanitizer = :strict` setting...

**Comment by robrobbins** [comment]
Right. Not that I know of but we can ask...

**Comment by ghost** [comment]
+1

**Comment by misha-slyusarev** [comment]
Still have the issue when using Devise:

ActiveModel::MassAssignmentSecurity::Error in Devise::SessionsController#create
Can't mass-assign protected attributes: action, modifications

Have you ever managed to make it work along with Devise?

**Comment by harley** [comment]
released 0.1.5 -- sorry for forgetting about this. to be honest, i'm not really enthusiastic about in attr_accessible because strong_parameters is preferred in rails 4 style :)

@misha-slyusarev did you manage to fix that devise error? yeah i have used this with devise without issues in the past but i don't remember if i ran into something like this or not. if you still have that error and wanna give it another try, i'd be happy to take a closer look
